export default {
    testBaseUrl:{url:"/api","desc":"测试环境配置跨域的"},//nginx配置跨域代理处理
    testBaseUrlNoProxy:{url:"http://10.74.20.65/api","desc":"测试环境"},
    baseUrl:{url:"http://10.74.20.65:5000/api","desc":"生产环境配置跨域的"},//nginx配置跨域代理处理
    baseUrlNoProxy:{url:"http://10.74.20.65/api","desc":"生产环境"},
    login:{url:"/v1/token","desc":"登录"},	
    projects:{url:"/v1/base_data/projects","desc":"工程列表"},
    updateProject:{url:"v1/base_data/update","desc":"修改工程"},
    delProject:{url:"/v1/base_data/delete","desc":"删除指定工程"},
    sheetsMsg:{url:"/v1/file/sheets","desc":"上传文件获取sheet数量"},
    sheetData:{url:"/v1/file/upload","desc":"上传文件获取sheet数据"},
    baseDataPage:{url:"/v1/base_data/pages/","desc":"分页获取原始数据"},
    isPrimaryKey:{url:"/v1/base_data/is_primary_key","desc":"检查某列是否可以设置为主键"},
    saveTag:{url:"/v1/base_data/save_tag","desc":"设置标签存储设置信息"},
    createProjectName:{url:"/v1/base_data/create_name","desc":"设置工程名"},
    modelList:{url:"/v1/model/list","desc":"获取指定工程下的模型列表数据"},
    delModelList:{url:"/v1/model/delete","desc":"删除模型，包括该节点下的所有子节点都要删除"},
    updateModelList:{url:"/v1/model/update","desc":"修改模型：包括修改模型名称和备注"},
    confirmData:{url:"/v1/base_data/confirm","desc":"获取用户确认数据信息"},
    confirmDataPage:{url:"/v1/base_data/confirm/pages/","desc":"分页获取用户筛选后的数据信息"},
    factorDataPage:{url:"/v1/characteristics/factor/pages/","desc":"分页获取用户筛选后的数据信息"},
    factorCreate:{url:"/v1/characteristics/factor/create","desc":"在当前模型节点上创建子节点的特征因子"},
    lineChartSelects:{url:"/v1/characteristics/line_chart/init","desc":"获取指定模型下的折线图/箱线图的特征名,分组或shape列表初始化数据"},
    lineChartData:{url:"/v1/characteristics/line_chart/data","desc":"根据查询条件获取指定模型下的折线图数据"},
    pointChartSelects:{url:"/v1/characteristics/point_chart/init","desc":"获取指定模型下散点图的初始化数据"},
    pointChartData:{url:"/v1/characteristics/point_chart/data","desc":"获取指定模型下散点图的初始化数据"},
    g2gData:{url:"/v1/characteristics/chart/g2g","desc":"组对组/组对整体分析接口"},
    boxChartData:{url:"/v1/characteristics/box_chart/data","desc":"根据查询条件获取指定模型下的箱线图数据接口"},
    engineList:{url:"/v1/enginee/ylist","desc":"获取特征工程-重要度Y列表集合数据"},
    engineVip:{url:"/v1/enginee/get_vip","desc":"根据选取的Y列表值获取重要度数据接口"},
    modelConfigList:{url:"/v1/build/config/list","desc":"获取模型参数配置列表集合接口"},
    algorithmList:{url:"/v1/build/config/algorithm/list","desc":"获取模型构建-指定模型类型下的算法列表集合数据"},
    algorithmParam:{url:"/v1/build/config/algorithm/param","desc":"获取对应算法下的相关参数数据"},
    fittingBuild:{url:"/v1/build/fitting","desc":"拟合接口"},
    scoreRegression:{url:"/v1/score/regression","desc":"获取回归的模型评分数据"},
    engineeGetCorr:{url:"/v1/enginee/get_corr","desc":"根据选取的Y列表值获取特征工程-相关性数据"},
    engineeAutoCorr:{url:"/v1/enginee/auto_corr/init/pages/","desc":"特征工程-特征间相关性矩阵"},
    engineeAutoCorrVar:{url:"/v1/enginee/auto_corr/variable/pages/","desc":"特征工程-剔除变量数据"},
    extractMethods:{url:"/v1/enginee/extract/methods","desc":"特征工程-获取特征抽取初始化抽取方法列表接口"},
    extractInits:{url:"/v1/enginee/extract/init","desc":"特征工程-根据抽取方法获取特征抽取初始数据"},
    extractDataPage:{url:"/v1/enginee/extract/data/pages/","desc":"特征工程-根据抽取方法和主成分获取特征抽取结果数据接口"},
    standardConfig:{url:"/v1/enginee/standard/config","desc":"特征工程-获取因子标准化处理"},
    standardDataPage:{url:"/v1/enginee/standard/data/pages/","desc":"特征工程-获取特征标准化数据接口"},
    encodeLabelPage:{url:"/v1/enginee/encode/label/pages/","desc":"获取特征编码转换文本列数据接口"},
    encodeDataPage:{url:"/v1/enginee/encode/data/pages/","desc":"实现特征编码转换接口"},
    forecastInitList:{url:"/v1/model/forecast/list", "desc": "获取指定工程下的回归或分类模型列表接口"},
    forecastResult:{url:"/v1/forecast/result", "desc":"模型预测接口"},
    featureBuildData:{url:"/v1/enginee/feature/data", "desc":"获取特征构建数据程"},
    featureCalculateMethod:{url:"/v1/enginee/calculate/methods", "desc":"获取计算方法列表数据"},

   
}
